import torch
import torch.optim as optim
import numpy as np
from meta_learning.maml import create_maml_model
from meta_learning.adapt import compute_loss_on_task
import config.settings as settings

def train_meta(tasks, input_dim, output_dim, device='cpu'):
    """
    Meta-training loop using MAML.
    tasks: list of task dicts (as generated by TaskGenerator)
    """
    maml = create_maml_model(input_dim, output_dim, inner_lr=settings.INNER_LEARNING_RATE)
    maml.to(device)
    meta_optimizer = optim.Adam(maml.parameters(), lr=settings.META_LEARNING_RATE)
    
    num_tasks = len(tasks)
    for iteration in range(settings.NUM_ITERATIONS):
        meta_optimizer.zero_grad()
        
        # Sample a batch of tasks
        task_indices = np.random.choice(num_tasks, size=settings.META_BATCH_SIZE, replace=False)
        meta_loss = 0.0
        
        for idx in task_indices:
            task = tasks[idx]
            # Clone model for this task
            learner = maml.clone()
            # Inner loop: adapt on support set
            support_loss = compute_loss_on_task(learner, task, mode='support')
            learner.adapt(support_loss)
            # Outer loss on query set
            query_loss = compute_loss_on_task(learner, task, mode='query')
            meta_loss += query_loss
        
        meta_loss /= settings.META_BATCH_SIZE
        meta_loss.backward()
        meta_optimizer.step()
        
        if iteration % 100 == 0:
            print(f"Iteration {iteration}, meta loss: {meta_loss.item()}")
    
    # Save final model
    torch.save(maml.state_dict(), settings.MODEL_SAVE_PATH)
    return maml
